- id: '1778010341339'
  alias: Sprinkler AM PM Schedule
  trigger:
  - platform: time
    at: 05:30:00
  - platform: time
    at: '17:30:00'
  condition:
  - condition: state
    entity_id: input_boolean.sprinkler_rain_skip
    state: 'off'
  action:
  - service: script.sprinkler_run_all_zones
  mode: single
